application: play-ayu
version: 1
runtime: go
api_version: go1

handlers:
 - url: /(.*\..*)$
   static_files: static/\1
   upload: static/.*
 - url: /
   static_files: static/index.html
   upload: static/index.html
 - url: /.*
   script: _go_app
